### ISSUE TITLE
static function parseDateStatic uses $this

### ISSUE THREAD

**Issue by ctot-nondef** [acdh-oeaw/AkSearchExtend#1]
the static function [parseDateStatic](https://github.com/acdh-oeaw/AkSearchExtend/blob/dc75287305100f659ef177011188505464a9640a/src/aksearchExt/Alma.php#L203) uses $this to acess its classes `dateConverter` wich throws an exception

temporarily turned off in production [here](https://github.com/acdh-oeaw/AkSearchExtend/blob/dc75287305100f659ef177011188505464a9640a/src/aksearchExt/container/ItemData.php#L82)

**Comment by zozlak** [comment]
The method has been introduced by @nczirjak-acdh in the db417de0556d23ea8fe7b703a685619027db168f . On one hand it looks like this piece of code was moved from somewhere but on the other the commit only adds this method and does not remove anything from other place in the code.

@nczirjak-acdh do you maybe remember where you took it from?

**Comment by nczirjak-acdh** [comment]
I think  i copied this function from the basic alma.php and just extended one or two rows.

**Comment by zozlak** [comment]
Ah, I forgot a lot of VuFind and whole AkSearch code is not shipped as composer packages!
Ok, I think I'll be able to deal with it now.

**Comment by zozlak** [comment]
@ctot-nondef how can I try to reproduce the error?
